### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by ayubowan2u** [moreginger/xbmc-plugin.video.ted.talks#72]
Hello, just downloaded the latest generic OpenElec image and installed on my PC. Added this add-on - video works OK but there is no audio. Only subtitles are visible. Any pointers to fix this issue is appreciated.

**Comment by ayubowan2u** [comment]
The problem was resolved by setting a higher data rate in the options. The default value was set very low.

**Comment by moreginger** [comment]
Ah OK so no audio was a codec issue.

Yes the default rate is low. IIRC back in the day TED only gave that complete URL for a resource, and the others were made by modification. That same base URL is still available, but it looks like they now give complete URLs for the different rates.  The right solution probably involves looking at those rather than constructing the URL manually, and defaulting to a higher value with appropriate fallback. I've changed this issue to cover that approach.

**Comment by moreginger** [comment]
We negotiate the av streams differently now (using m3u8 playlists) so closing this issue.
